name = "spectrum/whalepools"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'spectrum/whalepools'"

[repository]
user = "spectrum"
project = "whalepools"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"
