name = "spectrum/splash"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'spectrum/splash'"

[repository]
user = "spectrum"
project = "splash"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
